spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=growly
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        
  application:
    name: backend

jwt:
  secret: your-256-bit-secret-key-here-make-it-long-and-secure-for-production
  expiration: 86400000  # 24 hours in milliseconds
